/**
 * Puzzora Image Assets - Vite-processed for web views
 * 
 * CRITICAL: Images must be imported via Vite to work in web-based Custom Post Types.
 * This file uses Vite's import.meta.glob to import all puzzle images at build time.
 * 
 * Why this works:
 * 1. Vite processes these imports during build
 * 2. Each image gets a content hash for caching
 * 3. Vite returns proper URLs like /assets/puzzle-1.a1b2c3d4.png
 */

// ============================================
// PRE-BUILT ASSET MAP (Generated by Vite)
// ============================================

// Using Vite's glob pattern to import all puzzle images
const assetModules = import.meta.glob<{ default: string }>('/assets/puzzle-images/*.png', { eager: true });

// Create a map of image names to their Vite-processed URLs
const ASSET_URLS: Record<string, string> = {};

for (const [path, mod] of Object.entries(assetModules)) {
  // Extract filename from path: "/assets/puzzle-images/puzzle-1.png" -> "puzzle-1.png"
  const filename = path.split('/').pop() || '';
  ASSET_URLS[filename] = mod.default;
  console.log(`[ImageAssets] Loaded: ${filename} -> ${mod.default}`);
}

// Fallback for when glob doesn't work - hardcoded URLs that work in Devvit
const FALLBACK_URLS: Record<string, string> = {
  'puzzle-1.png': '/assets/puzzle-images/puzzle-1.png',
  'puzzle-2.png': '/assets/puzzle-images/puzzle-2.png',
  'puzzle-3.png': '/assets/puzzle-images/puzzle-3.png',
  'puzzle-4.png': '/assets/puzzle-images/puzzle-4.png',
  'puzzle-5.png': '/assets/puzzle-images/puzzle-5.png',
  'puzzle-6.png': '/assets/puzzle-images/puzzle-6.png',
  'puzzle-7.png': '/assets/puzzle-images/puzzle-7.png',
  'puzzle-8.png': '/assets/puzzle-images/puzzle-8.png',
  'puzzle-9.png': '/assets/puzzle-images/puzzle-9.png',
  'puzzle-10.png': '/assets/puzzle-images/puzzle-10.png',
  'puzzle-11.png': '/assets/puzzle-images/puzzle-11.png',
  'puzzle-12.png': '/assets/puzzle-images/puzzle-12.png',
  'puzzle-13.png': '/assets/puzzle-images/puzzle-13.png',
  'puzzle-14.png': '/assets/puzzle-images/puzzle-14.png',
  'puzzle-15.png': '/assets/puzzle-images/puzzle-15.png',
  'puzzle-16.png': '/assets/puzzle-images/puzzle-16.png',
  'puzzle-17.png': '/assets/puzzle-images/puzzle-17.png',
  'puzzle-18.png': '/assets/puzzle-images/puzzle-18.png',
  'puzzle-19.png': '/assets/puzzle-images/puzzle-19.png',
  'puzzle-20.png': '/assets/puzzle-images/puzzle-20.png',
};

// ============================================
// PUBLIC API
// ============================================

/**
 * Get the Vite-processed URL for a puzzle asset
 * @param filename - The image filename (e.g., "puzzle-1.png")
 * @returns The resolved URL for use in CSS backgroundImage or <img> src
 */
export function getPuzzleAssetUrl(filename: string): string {
  // Try Vite-processed URL first
  const viteUrl = ASSET_URLS[filename];
  if (viteUrl) {
    console.log(`[ImageAssets] Using Vite URL for: ${filename} -> ${viteUrl}`);
    return viteUrl;
  }
  
  // Fallback to direct asset path
  console.warn(`[ImageAssets] Vite URL not found for ${filename}, using fallback`);
  const fallback = FALLBACK_URLS[filename];
  if (fallback) {
    return fallback;
  }
  
  // Ultimate fallback
  console.error(`[ImageAssets] Even fallback failed for ${filename}, using puzzle-1.png`);
  return '/assets/puzzle-images/puzzle-1.png';
}

/**
 * Get all puzzle image filenames
 */
export function getPuzzleImageFilenames(): string[] {
  return Object.keys(FALLBACK_URLS);
}

/**
 * Debug: Log all loaded assets
 */
export function debugLogAssets(): void {
  console.log('[ImageAssets] === Loaded Assets ===');
  for (const [filename, url] of Object.entries(ASSET_URLS)) {
    console.log(`  ${filename}: ${url}`);
  }
  console.log('[ImageAssets] Total Vite assets:', Object.keys(ASSET_URLS).length);
  console.log('[ImageAssets] ======================');
}
